### PR TITLE
Return 1 on error or mistakes

### PR DESCRIPTION
**Pull request by peteruithoven**
See #39

### CODE REVIEW

**Comment by pantor** [comment]
I would personally prefer a mistake counter in the application class, that would be an easier and shorter implementation. It could also be useful if we want to print a summary like `1 error and 5 warnings` in the future, and I think most linters do that. But you're right, we should exit with 1 if mistakes were found.

**Comment by peteruithoven** [comment]
I can imagine you'd want to separate the checking from the visual output a bit more. Currently we're getting the mistakes per file and printing those in the same function. I can imagine it has 3 phases:
1. Get a list of files
2. Check those files and store mistakes
3. Output those mistakes. 

That would make it easier to alter just the output part for example.

But seeing that the parser branch contains [quite some changes](https://github.com/elementary/vala-lint/compare/parser) doing that in the master branch didn't make sense yet.

**Comment by pantor** [comment]
Yeah, I was thinking about separating that as well. I would be really cool to have different output formatters. You can go ahead, the PR for the new parser does not change the Application class. 😉

**Comment by peteruithoven** [comment]
Alright, I'm working on that instead. I don't really know Vala so that's going to be interesting.

**Pull request closed without merging**
