### PR TITLE
Add file tests

### PR DESCRIPTION
**Pull request by pantor**
For file tests, complete `*.vala` files are linted and checked for given mistakes at given lines. Therefore, three examples files from different elementary projects are added.

### CODE REVIEW

**Comment by pantor** [comment]
I think the other way round, we should merge this as soon as possible to make sure all tests work as expected.

**Comment by jeremypw** [comment]
This assumes you have an independent way of knowing how many true mistakes are in the files and where they are (which is hard-coded in the test).  If you got this information by running vala-lint then it only checks for changes in future. (Either more or less mistakes detected - which could either be a regression or an improvement in a checker).  Adding new checkers is likely to required changing the hard-coded values in this test.

However, if you prefer to merge it now I would not object.

**Comment by pantor** [comment]
You're right, we can in principle check only for false positive errors. But I manually added a few errors for each check in the test files, so I can make sure that these get detected. Either way, I would prefer to merge it sooner rather than later.

**Comment by jeremypw** [comment]
Unfortunately my main machine is now out of action and I am having to use a very old and slow 32-bit machine to keep in touch so I cannot properly test at the moment. Maybe David or Dan can oblige. I hope to be back in action in a couple of weeks.

**Pull request closed without merging**
