### PR TITLE
Move from Travis to Github Actions

### PR DESCRIPTION
**Pull request by pantor**
In addition, the CI works now. :wink: I'm note sure if this is in line with elementary though.

### CODE REVIEW

**Comment by danrabbit** [comment]
Totally in favor of GitHub actions, but it looks like the Travis build is failing because of linting errors. Are we sure the linter is being run correctly in GitHub actions here?

**Comment by pantor** [comment]
Travis fails as the Vala-Lint version in apt is somehow not up-to-date. In comparison, Github Actions uses the current build for linting. This does work, a linting error in the CI looks like [this](https://github.com/elementary/vala-lint/runs/209265356).

**Comment by jonafato** [comment]
@pantor Per your comment at https://github.com/elementary/vala-lint/commit/eb35799111a89601a020e129386a325a672df9d7#commitcomment-34732812, it seems like this is a Docker issue rather than an apt one. The PPA looks [up to date](https://launchpad.net/~elementary-os/+archive/ubuntu/daily/), but the Docker Hub tags are [six months behind](https://hub.docker.com/r/elementary/docker/tags).

**Comment by pantor** [comment]
@jonafato I see, this might be the reason. How can we update the docker containers?

I think to use the build version of vala-lint to lint itself makes sense, as well as to move from Travis to Github Actions. While both could of course be implemented independently, I'm still in favor of this PR as it is.

**Comment by jonafato** [comment]
>How can we update the docker containers?

@pantor I've created a new issue with a couple of references from other PRs and issues at #96.

**Pull request merged**
