### PR TITLE
Add Double Spaces Check

### LINKED ISSUE #16: Add check for double-spaces
Check, if there are more than one spaces _in_ a line (but not on the beginning).
Example:
`____print__("test");`

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38204343-add-check-for-double-spaces?utm_campaign=plugin&utm_content=tracker%2F45980444&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45980444&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pantor**
Fixes #16

### CODE REVIEW

**Comment by davidmhewitt** [comment]
I would also argue that there are sometimes other uses for double spaces within code, see for example here:
https://github.com/elementary/mail/blob/rewrite/src/MainWindow.vala#L40-L44

I don't know whether doing that is official elementary code style. But I think that looks neater than not having the extra spaces in there to align them.

**Comment by jeremypw** [comment]
I do not think that is elementary style - and it would make it difficult or impossible to check for unexpected spaces.

**Comment by jeremypw** [comment]
@pantor Do you think you will be able to exclude aligned inline comments?

**Comment by pantor** [comment]
@jeremypw  I hope my latest commits do the trick.

**Comment by jeremypw** [comment]
Unfortunately my main machine is out of action at the moment and I cannot get this to compile on an older machine at the moment. Maybe Dan or David will check this?  It might be a while before I can review.

**Comment by jeremypw** [comment]
Probably need to specify a minimum version number for libgee.

**Pull request merged**
